ALTER IGNORE TABLE `%%TABLENAME%%` ADD `ench_index` int(11) NOT NULL AFTER `id`;
ALTER IGNORE TABLE `%%TABLENAME%%` ADD `ench` int(11) NOT NULL AFTER `ench_index`;
ALTER IGNORE TABLE `%%TABLENAME%%` ADD `level` int(11) NOT NULL AFTER `ench`;