verbosity: 2
check-interval: 600
check-plugin-updates: true
no-creative: true
mysql:
  host: localhost:3306
  user: root
  pass: pass
  db: minecraft
  table: InventorySQL
messages:
  no-modif: 'No modifications'
  modif: '%s items added, %s items removed, %s items pendings'
  no-online: 'None of these players were online..'
  check-n-players: 'Checking %s player(s)'
  check-all-players: 'Checking all players...'
  check-yourself: 'Checking yourself...'