check-interval: 600
after-login-delay: 1
check-plugin-updates: true
no-creative: true
multiworld: true
lightweight-mode: false
allow-unsafe-ench: false
debug: false
mysql:
  host: localhost:3306
  user: root
  pass: pass
  db: minecraft
  table: InventorySQL
backup:
  enabled: true
  interval: 600
  cleanup-days: 5
messages:
  no-modif: 'No modifications'
  modif: '%s items added, %s items removed, %s items pendings'
  no-online: 'None of these players were online..'
  check-n-players: 'Checking %s player(s)'
  check-all-players: 'Checking all players...'
  check-yourself: 'Checking yourself...'
update-events:
  - join
  - quit
  - changeworld
  - respawn
  - bedenter
  - bedleave