name: InventorySQL
main: alexoft.InventorySQL.Main
author: ThisIsAreku
version: 0.6.2
description: Sync your inventory on MySQL
commands:
    invSQL:
        description: InventorySQL
        usage: /invSQL