name: InventorySQL
main: alexoft.InventorySQL.Main
author: ThisIsAreku
version: 0.5.3${build.number}
description: Sync your inventory on MySQL
commands:
    invSQL:
        description: InventorySQL
        usage: /invSQL