name: InventorySQL
main: alexoft.InventorySQL.Main
author: ThisIsAreku
website: http://alexoft.x10.mx/
version: 0.6.5
description: Sync your inventory on MySQL
commands:
    invSQL:
        description: InventorySQL
        usage: /invSQL